### ISSUE TITLE
Seamount tests

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#31]
I have started from the MOM6-examples seamounts and made some changes based on Harper's suggestions. First, a word on the original seamount test cases. I believe it isn't testing pressure gradient errors in two ways: (a) it is a ridge, not a seamount and (b) the vertical density gradient is linear, which Beckmann showed is a special case for sigma-coordinate models in which the errors go to zero.

Onward to Harper's version. The goal is to drive barotropic tides in such a way as to radiate baroclinic tides. They should spiral out, somewhat like in these figures
![image](https://cloud.githubusercontent.com/assets/444446/24119290/82afa75c-0d65-11e7-993d-9970cf67cd26.png)
![image](https://cloud.githubusercontent.com/assets/444446/24119307/8ac2909e-0d65-11e7-858c-33ad3eca0120.png)

These are from the "layer" directory, the "e" field at about 800 m depth. The boundaries are not entirely happy.

The "rho" directory appears not to apply the TIDES.

**Comment by kshedstrom** [comment]
I was wrong about the "rho" directory. It is failing:

> Backtrace for this error:
> #0  0x7F74BD004D87
> #1  0x7F74BD003F80
> #2  0x7F74B904C65F
> #3  0xEA783D in __regrid_solvers_MOD_solve_linear_system at regrid_solvers.F90:116 (discriminator 16)
> #4  0xF51D16 in __regrid_edge_slopes_MOD_edge_slopes_implicit_h3 at regrid_edge_slopes.F90:156
> #5  0xCB8F98 in __mom_regridding_MOD_regridding_set_ppolys at MOM_regridding.F90:2616 (discriminator 24)
> #6  0xCD6F4D in __mom_regridding_MOD_build_rho_column at MOM_regridding.F90:1583 (discriminator 24)
> #7  0xCD96DB in __mom_regridding_MOD_build_rho_grid at MOM_regridding.F90:1414 (discriminator 24)
> #8  0xCE07BF in __mom_regridding_MOD_regridding_main at MOM_regridding.F90:848
> #9  0xF6AA1D in __mom_ale_MOD_ale_main at MOM_ALE.F90:405
> #10  0x10CD972 in __mom_MOD_step_mom at MOM.F90:1152
> #11  0xB49AD6 in MAIN__ at MOM_driver.F90:469

It is failing at i = j = 21, with count_nonzero_layer = 18 when it should be 15. The last five values of h0 are:

> 9.9999999999994e-10
> 9.9999999999997e-10
> 1e-09
> 1e-09
> 1e-09

This is being compared to threshold, which is 1e-09 (line 1533 of MOM_regridding.F90).
